version: '3.8'

services:
  application:
    container_name: concert_app_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

  redis:
    image: bitnami/redis:7.4
    container_name: redis_prod
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_prod_data:/bitnami/redis/data
    restart: always
    networks:
      - app-network

volumes:
  redis_prod_data:

networks:
  app-network:
    driver: bridge