spring:
  application:
    name: hhp7_concert_reservation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mydatabase
    username: myuser
    password: secret
    hikari:
      auto-commit: false
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: concert

logging:
  level:
    org:
      springframework: DEBUG
    com:
      hhp7:
        concertreservation:
          repository:
          service: info
          controller: info
          component: info

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus, beans, env, conditions
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

#### 데이터 플랫폼 EndPoint 설정
dataplatform:
  url: http://localhost:8080/api/dataplatform/reservations

#### 대기열 구현체 설정 : Default - DB
app:
  queue:
    provider: "REDIS"
    policy:
      max-concurrent-user-threshold: 1.2
      max-concurrent-user: 50
      waiting-token-duration: 6
      active-token-duration: 3

springdoc:
  api-docs:
    path: /v3/api-docs       # 기본값: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html   # Swagger UI 접속 경로 (기본값: /swagger-ui.html)